### ISSUE TITLE
No buttons work

### ISSUE THREAD

**Issue by Basm360** [WillNichols726/target-lock#8]
The buttons in chat do nothing and the double damage button is ENORMOUS. Foundry 9.0. All other modules deactivated when testing

**Comment by Zadantur** [comment]
> The buttons in chat do nothing and the double damage button is ENORMOUS. Foundry 9.0. All other modules deactivated when testing

Sounds exactly like the problem I addressed in the previous issue thread.  Doing the steps i outlined will get the buttons to work again, but won't completely fix the formatting.
